--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/CustomVanillaEnchants
build-by-default: true
branches:
- master
projects:
  CustomVanillaEnchants:
    path: ""
    icon: icon.png
    libs:
      - src: muqsit/arithmexp/arithmexp
        version: ^0.1.29
...
